---
- name: Install nginx server
  hosts: node
  become: true
  tasks:
    - name: Install nginx server
      yum:
        name: nginx
        state: present
    - name: Start service
      service:
        name: nginx
        state: started
