- name: Task level variable
  hosts: localhost
  vars_files:
  - variable.yaml
  tasks:
   - name: Get variable from varaible.yaml file
     debug:
       msg: "I am learning {{Course}}, Trainer is {{Trainer}} With duration is {{Duration}} "